"""Create table ElementImage

Revision ID: 15809d52f448
Revises: 59faaf173275
Create Date: 2023-01-14 01:41:29.815871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15809d52f448'
down_revision = '59faaf173275'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('element_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('element_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['element_id'], ['element.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('element_image')
    # ### end Alembic commands ###
